### ISSUE TITLE
PGM: Pursuit of Happyness XML issue

### ISSUE THREAD

**Issue by ghost** [UnicraftNetwork/Issues#1]
When a player respawn doesn't give any item to inventory. (probably an issue with the class system of the map)

**Comment by teszeo** [comment]
Sorry @FudyMC but that map is not on our repo, maybe you saw another map with a different name? or similar?

**Comment by teszeo** [comment]
Fixed https://github.com/ElMedievo-UdeC/maps/commit/e26f0aed603fd66e7470e0688a6a4785e13e4454
